# Generated by Django 5.2.4 on 2025-07-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('course', models.CharField(choices=[('B.Tech CSE', 'B.Tech - Computer Science'), ('B.Tech IT', 'B.Tech - Information Technology'), ('B.Tech ECE', 'B.Tech - Electronics & Communication'), ('B.Tech ME', 'B.Tech - Mechanical Engineering'), ('BCA', 'BCA - Bachelor of Computer Applications'), ('M.Tech CSE', 'M.Tech - Computer Science'), ('M.Tech IT', 'M.Tech - Information Technology')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('qualification_percentage', models.FloatField()),
                ('unique_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
